name: first_workflow
on:  workflow_dispatch #this is a keyword that makes sure the user can trigger the job manually

jobs: 
  david_first_job:
    runs-on: ubuntu-latest
    steps:
      -  name: print greetings
         run: echo "Hello world"
      -  name: print goodbye
         run: echo "Done, Goodbye"
